### ISSUE TITLE
 get stuck  running erfnet model on Jetson TX2 

### ISSUE THREAD

**Issue by EthanCalvin** [Eromera/erfnet_pytorch#19]
Hi, I want to run the erfnet model on Jeson tx2.

- I installed pytorch without problems and cuda 9.0 with cudnn 7.0
ex) i checked by 'import torch' , i checked by 'nvcc --version'

but When I try to run erfnet code, I got stuck

"RuntimeError : cuda runtime error(7) : too many resources requested for launch at /home/nvidia/pytorch/aten/src/THCUNN/im2col.h"

please help me!.

[](url)

**Comment by ShreyasSkandan** [comment]
Did you find a solution to this problem?

I've got the same problem with the exact same version of CUDA and CuDNN.

**Comment by ShreyasSkandan** [comment]
This problem has been fixed if you're still interested.

This has to do with CUDA 9.0 attempting to allocate more registers to each thread. This can be fixed by setting a launch bound on the cuda kernels in **im2col.h**. You should be able to just pull the latest pytorch version and re-install it and it would work.

For more details look at this thread:
https://github.com/pytorch/pytorch/issues/7680

**Comment by Eromera** [comment]
Hi! Sorry for the late reply. I recently tried in Jetson TX2 with the latest CUDA and compiling PyTorch from scratch and it worked perfectly. So I'll close the issue and if you are still having trouble please reopen!

**Comment by MrLinNing** [comment]
@ShreyasSkandan 
Hi, I have compiling PyTorch from scrath, but I still meet the problem. Which file to add the `__launch_bounds__(1024)` ?

**Comment by MrLinNing** [comment]
@Eromera 
Can you give me your pytorch wheel on TX2 ？Or more details about installing the pytorch on TX2？I have try many times but the problem still exists. [this ](https://github.com/pytorch/pytorch/issues/7680#issuecomment-450142947)

**Comment by Eromera** [comment]
Hi, I dunno about the launch_bounds issue but I followed [this procedure](https://github.com/andrewadare/jetson-tx2-pytorch). Had some issues I think but it ends up compiling successfully

**Comment by MrLinNing** [comment]
What's your version of Pytorch, CUDA and CUDNN on TX2?  @Eromera

**Comment by Eromera** [comment]
Last pytorch from source, CUDA 9.0 and CuDNN 7
