### ISSUE TITLE
data with cityscape doesnot work

### ISSUE THREAD

**Issue by zhhtu** [Eromera/erfnet_pytorch#5]
hi, thanks for the code first, but it seems code doesnot work with cityscape dataset currently. I'm using python3.6 with pytorch version: 0.2.0_4, it crashed after several training steps with:

THCudaCheck FAIL device-side assert triggered, update_grad)input_fn()
RuntimeError: cuda runtime error(59): device-side assert triggered at /opt/conda/conda-bld/pytorch/work/torch/lib/THCUNN/generic/Threshold.cu:66

**Comment by Eromera** [comment]
Hi, thanks for your message. The code that is uploaded works in cityscapes for me without any modification, and I believe I have the same Pytorch and python versions. Can you please give more info regarding the following things:

Is that the only output? If there is more can you comment the full error that you are getting?

Can you show in which line specifically is this error happening?

What is your gpu and what batch size are you using? Encoder or decoder training?

What CUDA and CuDNN versions are you using?

Thanks

**Comment by zhhtu** [comment]
hi Eromera thank you very much for the replay, here is the error when I trained the Encoder:
![screen shot 2017-11-29 at 11 08 30 am](https://user-images.githubusercontent.com/19236599/33356131-c13c400e-d4f5-11e7-9b63-20768e429f0c.png)
I'm using Titan X GPU with batch number "1" as been seen above. Also with CUDA 8.0, CuDNN 5.1.5

Another question is with my downloaded cityscape dataset, in Label train folder, I've got files ending with "_color.png" which is color version of labelling;  "labelids.png" which is one dimension [0-19] labelling image; So I looked into the code and choose the "_color.png" for the code, should that be right? Thank you.

**Comment by Eromera** [comment]
Hi, the error is related to the labels as I can see that it fails during the backprop in the loss function so I think the error is exactly related to your other question that you did below.

You mentioned that you chose _color.png, did you changed this in "dataset.py" file? Both labelids.png and color.png is not what you should use. You should use the Cityscapes "_labelTrainIds.png". You can create these images automatically by using the Cityscapes scripts that they have in their repository, specifically the script "scripts/preparation/createTrainIdLabelImgs.py". This will convert the "labelids.png" to labels ranging from 0 to 18 and 255 for ignore label, which is this "_labelTrainIds.png" that is loaded in my code. Please confirm if this fixes your error!

**Comment by zhhtu** [comment]
hi Eromera  Error confirmed, it is the dataset cased the problem! 
After running the scrips of cityscape, everything works fine.
Thank you very much!

**Comment by Eromera** [comment]
Thanks for confirming, glad to hear that it's working now!

**Comment by zhhtu** [comment]
hi Eromera, another question, I'm training with cityscapes right now following the readme file. In my understanding, I first train Encoder and then with Encoder's parameters train Decoder, so the whole model. Or I can use the pre-trained ImageNet Encoder parameters to train the Decoder Directly. But after one day's training with the pre-trained encoder parameters, I only got around 23% IoU, did I use the pre-trained parameters in the wrong way? I trained the decoder with code:
`
python main.py --savedir erfnet_training1 --datadir /home/datasets/cityscapes/ --num-epochs 150 --batch-size 6 --decoder --pretrainedEncoder "../trained_models/erfnet_encoder_pretrained.pth.tar"
`

**Comment by Eromera** [comment]
Hi, sorry for delay. 23% IoU is extremely low. Did you do any modification to the code? otherwise with the uploaded code you should get 72% at the end of the training. 

If you did some modification, you could try checking what you changed or you could clone the repository again with another name and try to do a new training.

What is the training error and validation error that you are getting during training? Could you check the automated_log.txt generated in the folder and tell me what these error values are across the first epochs (first 1-5 epochs) and at the end (150)?

**Comment by zhhtu** [comment]
hi Eromera, sorry for the delay, I've been training the model again, and the result is 70.16%. The problem is dataset I've downloaded, it seems there's something wrong with the dataset. After re-downloaded it, everything is ok. Thank you very much!

**Comment by Eromera** [comment]
70.16% still seems a bit low, default params should get you around 72%. Are you using default params or did you change anything? Cheers!

**Comment by zhhtu** [comment]
mm, I tried pre-trained with ImageNet weights, result is around 72% I use the original code

**Comment by Eromera** [comment]
Good! Those results make sense, thanks
